import type { Category, Area, Seller, Listing } from "./types";

// ข้อมูลตัวอย่าง — ใช้เมื่อยังไม่ได้เชื่อม Supabase (ทำให้เว็บ deploy แล้วเห็นของจริงทันที)

export const CATEGORIES: Category[] = [
  { id: "cat-veg", name: "ผัก", emoji: "🥬" },
  { id: "cat-fruit", name: "ผลไม้", emoji: "🍎" },
  { id: "cat-meat", name: "เนื้อสัตว์", emoji: "🍖" },
  { id: "cat-seafood", name: "อาหารทะเล", emoji: "🦐" },
  { id: "cat-dry", name: "ของแห้ง", emoji: "🌾" },
  { id: "cat-cooked", name: "อาหารปรุงสำเร็จ", emoji: "🍲" },
  { id: "cat-secondhand", name: "มือสอง", emoji: "📦" },
  { id: "cat-other", name: "อื่นๆ", emoji: "🛍️" },
];

export const AREAS: Area[] = [
  { id: "area-si-mum", province: "นครราชสีมา", market: "ตลาดสีมามุม" },
  { id: "area-suranaree", province: "นครราชสีมา", market: "ตลาดสุรนารี" },
  { id: "area-warorot", province: "เชียงใหม่", market: "ตลาดวโรรส (กาดหลวง)" },
  { id: "area-mueang-mai", province: "เชียงใหม่", market: "ตลาดเมืองใหม่" },
  { id: "area-thonburi", province: "กรุงเทพฯ", market: "ตลาดพลู" },
];

export const SELLERS: Seller[] = [
  {
    id: "seller-somchai",
    displayName: "ป้าสมใจ ผักสด",
    phone: "0812345678",
    phoneVerified: true,
    joinedAt: "2026-05-02T02:00:00.000Z",
    membershipExpiresAt: "2026-08-30T02:00:00.000Z",
    trialUsed: true,
    blocked: false,
    companyVerified: false,
  },
  {
    id: "seller-nid",
    displayName: "ร้านเจ๊นิด ทะเลสด",
    phone: "0898765432",
    phoneVerified: true,
    joinedAt: "2026-06-11T02:00:00.000Z",
    membershipExpiresAt: "2026-07-25T02:00:00.000Z",
    trialUsed: true,
    blocked: false,
    companyVerified: false,
  },
  {
    id: "seller-golf",
    displayName: "กอล์ฟ ของมือสอง",
    phone: "0801112222",
    phoneVerified: true,
    joinedAt: "2026-07-01T02:00:00.000Z",
    membershipExpiresAt: null, // อยู่ช่วงทดลอง
    trialUsed: false,
    blocked: false,
    companyVerified: false,
  },
];

export const LISTINGS: Listing[] = [
  {
    id: "l-1",
    sellerId: "seller-somchai",
    title: "ผักบุ้งไทยสด เก็บเช้านี้",
    description: "ผักบุ้งไทยสดใหม่ เก็บจากแปลงเช้านี้ กรอบหวาน มัดใหญ่",
    price: 15,
    unit: "มัด",
    categoryId: "cat-veg",
    areaId: "area-si-mum",
    images: [],
    status: "active",
    deliveryMethod: "meetup",
    createdAt: "2026-07-14T01:00:00.000Z",
    reportCount: 0,
    flaggedKeywords: [],
  },
  {
    id: "l-2",
    sellerId: "seller-somchai",
    title: "มะเขือเทศราชินี",
    description: "มะเขือเทศราชินีหวานฉ่ำ ปลูกเอง ไม่ใช้สารเคมี",
    price: 45,
    unit: "บาท/กก.",
    categoryId: "cat-veg",
    areaId: "area-si-mum",
    images: [],
    status: "active",
    deliveryMethod: "meetup",
    createdAt: "2026-07-13T04:00:00.000Z",
    reportCount: 0,
    flaggedKeywords: [],
  },
  {
    id: "l-3",
    sellerId: "seller-nid",
    title: "กุ้งแชบ๊วยสด ไซซ์ใหญ่",
    description: "กุ้งแชบ๊วยสดๆ จากทะเล ตัวใหญ่ เนื้อแน่น",
    price: 320,
    unit: "บาท/กก.",
    categoryId: "cat-seafood",
    areaId: "area-warorot",
    images: [],
    status: "active",
    deliveryMethod: "meetup",
    createdAt: "2026-07-14T00:30:00.000Z",
    reportCount: 0,
    flaggedKeywords: [],
  },
  {
    id: "l-4",
    sellerId: "seller-nid",
    title: "ปลาทูสด",
    description: "ปลาทูแม่กลองสด ตัวโต เหมาะทำต้มยำ ทอด",
    price: 25,
    unit: "ตัว",
    categoryId: "cat-seafood",
    areaId: "area-warorot",
    images: [],
    status: "active",
    deliveryMethod: "meetup",
    createdAt: "2026-07-12T05:00:00.000Z",
    reportCount: 0,
    flaggedKeywords: [],
  },
  {
    id: "l-5",
    sellerId: "seller-golf",
    title: "จักรยานพับได้ มือสอง สภาพดี",
    description: "จักรยานพับได้ ใช้งานน้อย ล้อ 20 นิ้ว เกียร์ชิมาโน่ 6 สปีด",
    price: 2500,
    unit: "ชิ้น",
    categoryId: "cat-secondhand",
    areaId: "area-thonburi",
    images: [],
    status: "active",
    deliveryMethod: "meetup",
    createdAt: "2026-07-13T08:00:00.000Z",
    reportCount: 0,
    flaggedKeywords: [],
  },
  {
    id: "l-6",
    sellerId: "seller-golf",
    title: "หม้อทอดไร้น้ำมัน มือสอง",
    description: "หม้อทอดไร้น้ำมัน 4.5 ลิตร ใช้ 2 ครั้ง อุปกรณ์ครบกล่อง",
    price: 890,
    unit: "ชิ้น",
    categoryId: "cat-secondhand",
    areaId: "area-thonburi",
    images: [],
    status: "active",
    deliveryMethod: "meetup",
    createdAt: "2026-07-11T09:00:00.000Z",
    reportCount: 0,
    flaggedKeywords: [],
  },
  {
    id: "l-7",
    sellerId: "seller-somchai",
    title: "ไข่ไก่สดคละเบอร์",
    description: "ไข่ไก่สดจากฟาร์ม คละเบอร์ แผงละ 30 ฟอง",
    price: 120,
    unit: "กล่อง",
    categoryId: "cat-other",
    areaId: "area-si-mum",
    images: [],
    status: "active",
    deliveryMethod: "meetup",
    createdAt: "2026-07-10T02:00:00.000Z",
    reportCount: 0,
    flaggedKeywords: [],
  },
  {
    id: "l-8",
    sellerId: "seller-nid",
    title: "หมูสามชั้นสด",
    description: "หมูสามชั้นสด ชั้นสวย เหมาะทำหมูกรอบ ปิ้งย่าง",
    price: 180,
    unit: "บาท/กก.",
    categoryId: "cat-meat",
    areaId: "area-mueang-mai",
    images: [],
    status: "active",
    deliveryMethod: "meetup",
    createdAt: "2026-07-14T02:00:00.000Z",
    reportCount: 0,
    flaggedKeywords: [],
  },
];
